import { useState } from 'react';
import { useTheme } from '../../context/ThemeContext';

type SettingsSection = 'business' | 'finance' | 'sales' | 'peripherals' | 'peripheralsAdvanced' | 'templates' | 'templatesAdvanced' | 'notifications' | 'security' | 'backups' | 'integrations' | 'appearance';

const sections: Array<{ id: SettingsSection; label: string; description: string }> = [
  { id: 'business', label: 'Business profile', description: 'Identity and contact details' },
  { id: 'finance', label: 'Taxes & pricing', description: 'Currency, tax, and rounding' },
  { id: 'sales', label: 'Sales & receipts', description: 'Checkout and invoice defaults' },
  { id: 'peripherals', label: 'POS peripherals', description: 'Printers, scanners, and devices' },
  { id: 'templates', label: 'Templates & printing', description: 'Receipt, invoice, and label layouts' },
  { id: 'notifications', label: 'Notifications', description: 'Alerts and delivery channels' },
  { id: 'security', label: 'Security & access', description: 'Sessions and permissions' },
  { id: 'backups', label: 'Backups & audit', description: 'Recovery and activity history' },
  { id: 'integrations', label: 'Integrations', description: 'Connected business tools' },
  { id: 'appearance', label: 'Theme & layout', description: 'Workspace preferences' },
];

function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: () => void }) {
  return <label className="setting-toggle"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={onChange} /><i /></label>;
}

function PeripheralCard({ name, detail, connected, onChange }: { name: string; detail: string; connected: boolean; onChange: () => void }) {
  return <div className={`peripheral-card ${connected ? 'connected' : ''}`}><div className="peripheral-icon">{name.slice(0, 1)}</div><div><strong>{name}</strong><span>{detail}</span></div><button className="ghost-button small" type="button" onClick={onChange}>{connected ? 'Disconnect' : 'Connect'}</button><span className={`status-badge ${connected ? 'success' : 'neutral'}`}>{connected ? 'Ready' : 'Offline'}</span></div>;
}

function TemplateCard({ name, description, selected, onClick }: { name: string; description: string; selected: boolean; onClick: () => void }) {
  return <button className={`template-card ${selected ? 'selected' : ''}`} type="button" onClick={onClick}><div className="template-thumbnail"><span /><span /><b /></div><strong>{name}</strong><small>{description}</small>{selected && <span className="status-badge success">Selected</span>}</button>;
}

export function Settings() {
  const { theme, setTheme } = useTheme();
  const [activeSection, setActiveSection] = useState<SettingsSection>('business');
  const [saved, setSaved] = useState(false);
  const [businessName, setBusinessName] = useState('Mwangi Electrical Supplies');
  const [email, setEmail] = useState('hello@mwangi-electricals.co.ke');
  const [currency, setCurrency] = useState('KES');
  const [taxRate, setTaxRate] = useState('16');
  const [receiptFooter, setReceiptFooter] = useState('Thank you for shopping with us');
  const [settings, setSettings] = useState({ lowStock: true, dailySummary: true, paymentAlerts: true, twoFactor: false, sessionExpiry: true, loginNotifications: true, requireCustomer: true, negativeStock: false, auditLog: true, autoBackup: true, compactMode: false, sounds: true });
  const [integrations, setIntegrations] = useState({ mpesa: true, email: true, sms: false });
  const [lastBackup, setLastBackup] = useState('Today at 02:00');
  const [showPermissions, setShowPermissions] = useState(false);
  const [confirmDeactivate, setConfirmDeactivate] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState('Modern receipt');
  const [templateType, setTemplateType] = useState('Receipt');
  const [paperSize, setPaperSize] = useState('80mm thermal');
  const [accentColor, setAccentColor] = useState('#1d4ed8');
  const [printDensity, setPrintDensity] = useState('Comfortable');
  const [printCopies, setPrintCopies] = useState('1');
  const [printSettings, setPrintSettings] = useState({ autoPrint: true, showLogo: true, showTax: true, showCustomer: true, openDrawer: true });
  const [testPrintSent, setTestPrintSent] = useState(false);
  const [peripherals, setPeripherals] = useState({ printer: true, scanner: true, drawer: true, display: false, scale: false });
  const [posSettings, setPosSettings] = useState({ offlineMode: true, suspendSales: true, barcodeSound: true, askQuantity: false, lockRegister: false, cashFloat: true });
  const [hardwareTested, setHardwareTested] = useState(false);
  const [deviceToAdd, setDeviceToAdd] = useState('Customer display · HDMI');
  const [addedDevices, setAddedDevices] = useState(['Epson TM-T20III · USB', 'Honeywell Voyager · USB', 'APG Vasario · Printer kick']);
  const [templateStyle, setTemplateStyle] = useState({ layout: 'Balanced', font: 'Inter', logoPosition: 'Centered', showSku: true, showNotes: false, showTerms: true });

  const toggle = (key: keyof typeof settings) => setSettings((current) => ({ ...current, [key]: !current[key] }));
  const saveChanges = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2400); };
  const togglePrintSetting = (key: keyof typeof printSettings) => setPrintSettings((current) => ({ ...current, [key]: !current[key] }));
  const sendTestPrint = () => { setTestPrintSent(true); window.setTimeout(() => setTestPrintSent(false), 2400); };
  const togglePosSetting = (key: keyof typeof posSettings) => setPosSettings((current) => ({ ...current, [key]: !current[key] }));
  const testHardware = () => { setHardwareTested(true); window.setTimeout(() => setHardwareTested(false), 2400); };
  const toggleTemplateStyle = (key: 'showSku' | 'showNotes' | 'showTerms') => setTemplateStyle((current) => ({ ...current, [key]: !current[key] }));
  const addDevice = () => { if (!addedDevices.includes(deviceToAdd)) setAddedDevices((current) => [...current, deviceToAdd]); };
  const runBackup = () => setLastBackup(`Just now · ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`);
  const exportData = () => {
    const exportPayload = { businessName, email, currency, taxRate, receiptFooter, settings, peripherals, selectedTemplate, paperSize, printSettings, exportedAt: new Date().toISOString() };
    const file = new Blob([JSON.stringify(exportPayload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(file);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'bizos-settings-export.json';
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="settings-workspace">
      <div className="settings-heading panel">
        <div><p className="eyebrow">System administration</p><h3>Settings</h3><p className="panel-subtitle">Configure how BizOs works for your business, team, and branches.</p></div>
        <div className="settings-heading-actions">{saved && <span className="save-confirmation">Changes saved</span>}<button className="primary-button small" type="button" onClick={saveChanges}>Save changes</button></div>
      </div>

      <div className="settings-layout">
        <aside className="settings-navigation panel">
          <p className="settings-nav-label">Configuration</p>
          {sections.map((section) => <button key={section.id} className={`settings-nav-item ${activeSection === (section.id === 'templates' ? 'templatesAdvanced' : section.id === 'peripherals' ? 'peripheralsAdvanced' : section.id) ? 'active' : ''}`} type="button" onClick={() => setActiveSection(section.id === 'templates' ? 'templatesAdvanced' : section.id === 'peripherals' ? 'peripheralsAdvanced' : section.id)}><strong>{section.label}</strong><small>{section.description}</small></button>)}
        </aside>

        <section className="settings-content panel">
          {activeSection === 'peripheralsAdvanced' && <>
            <div className="settings-section-header"><div><p className="eyebrow">POS control center</p><h3>Peripherals & POS operations</h3><p>Configure the active register, control checkout behavior, and diagnose connected hardware.</p></div><div className="settings-heading-actions">{hardwareTested && <span className="save-confirmation">Hardware check complete</span>}<button className="secondary-button small" type="button" onClick={testHardware}>Run hardware test</button></div></div>
            <div className="pos-register-banner"><div className="pos-register-mark">R1</div><div><strong>Register 01 · Main Branch</strong><span>Online · Last heartbeat 12 seconds ago</span></div><span className="status-badge success">Ready for sales</span></div>
            <div className="device-manager"><div><p className="settings-subheading">Add a device</p><span>Assign another supported device to this register.</span></div><div className="device-manager-form"><select value={deviceToAdd} onChange={(event) => setDeviceToAdd(event.target.value)}><option>Customer display · HDMI</option><option>Retail scale · Serial</option><option>Star TSP143 · Network</option><option>USB payment terminal</option></select><button className="secondary-button small" type="button" onClick={addDevice}>Add device</button></div><div className="device-chip-list">{addedDevices.map((device) => <span className="device-chip" key={device}>{device}<button type="button" aria-label={`Remove ${device}`} onClick={() => setAddedDevices((current) => current.filter((item) => item !== device))}>×</button></span>)}</div></div>
            <div className="settings-form-grid"><label className="field"><span>Active register</span><select defaultValue="Register 01 · Main Branch"><option>Register 01 · Main Branch</option><option>Register 02 · Main Branch</option><option>Register 03 · Industrial Area</option></select></label><label className="field"><span>Receipt printer</span><select defaultValue="Epson TM-T20III · USB"><option>Epson TM-T20III · USB</option><option>Star TSP143 · Network</option><option>None</option></select></label><label className="field"><span>Scanner input mode</span><select defaultValue="Keyboard wedge"><option>Keyboard wedge</option><option>Serial / COM</option><option>Manual SKU entry</option></select></label><label className="field"><span>Cash drawer trigger</span><select defaultValue="Open after cash payment"><option>Open after cash payment</option><option>Open for every sale</option><option>Manual only</option></select></label></div>
            <div className="settings-control-columns"><div><p className="settings-subheading">Checkout behavior</p><div className="settings-toggle-list"><Toggle label="Continue sales when offline" description="Keep the register available during a temporary network outage." checked={posSettings.offlineMode} onChange={() => togglePosSetting('offlineMode')} /><Toggle label="Suspend and resume sales" description="Allow cashiers to park an unfinished cart and return to it later." checked={posSettings.suspendSales} onChange={() => togglePosSetting('suspendSales')} /><Toggle label="Confirm item quantity" description="Ask for quantity after scanning the same item repeatedly." checked={posSettings.askQuantity} onChange={() => togglePosSetting('askQuantity')} /></div></div><div><p className="settings-subheading">Register safeguards</p><div className="settings-toggle-list"><Toggle label="Scanner feedback sound" description="Play a sound and show feedback after every successful scan." checked={posSettings.barcodeSound} onChange={() => togglePosSetting('barcodeSound')} /><Toggle label="Require register lock" description="Require the cashier PIN before switching users or registers." checked={posSettings.lockRegister} onChange={() => togglePosSetting('lockRegister')} /><Toggle label="Track opening cash float" description="Record the opening drawer balance before the first sale." checked={posSettings.cashFloat} onChange={() => togglePosSetting('cashFloat')} /></div></div></div>
            <div className="settings-action-row"><div><strong>Connected hardware</strong><span>{Object.values(peripherals).filter(Boolean).length} of {Object.keys(peripherals).length} devices are ready on this register.</span></div><button className="ghost-button small" type="button" onClick={testHardware}>Check connections</button></div>
          </>}
          {activeSection === 'templatesAdvanced' && <>
            <div className="template-customizer"><div><p className="settings-subheading">Customize selected template</p><span>Changes update the preview instantly for {selectedTemplate}.</span></div><div className="template-customizer-grid"><label className="field"><span>Layout</span><select value={templateStyle.layout} onChange={(event) => setTemplateStyle((current) => ({ ...current, layout: event.target.value }))}><option>Compact</option><option>Balanced</option><option>Spacious</option></select></label><label className="field"><span>Font</span><select value={templateStyle.font} onChange={(event) => setTemplateStyle((current) => ({ ...current, font: event.target.value }))}><option>Inter</option><option>Source Sans</option><option>Courier Prime</option></select></label><label className="field"><span>Logo position</span><select value={templateStyle.logoPosition} onChange={(event) => setTemplateStyle((current) => ({ ...current, logoPosition: event.target.value }))}><option>Left aligned</option><option>Centered</option><option>Right aligned</option></select></label></div><div className="template-customizer-toggles"><Toggle label="Show product SKU" description="Print the SKU below each line item." checked={templateStyle.showSku} onChange={() => toggleTemplateStyle('showSku')} /><Toggle label="Show item notes" description="Include notes or descriptions beneath line items." checked={templateStyle.showNotes} onChange={() => toggleTemplateStyle('showNotes')} /><Toggle label="Show payment terms" description="Print the configured payment terms at the bottom." checked={templateStyle.showTerms} onChange={() => toggleTemplateStyle('showTerms')} /></div></div>
            <div className="settings-section-header"><div><p className="eyebrow">Print center</p><h3>Templates & printing</h3><p>Shape every customer-facing document and control what reaches the printer.</p></div><div className="settings-heading-actions">{testPrintSent && <span className="save-confirmation">Test page sent</span>}<button className="secondary-button small" type="button" onClick={sendTestPrint}>Print test page</button></div></div>
            <div className="template-toolbar"><label className="field"><span>Template type</span><select value={templateType} onChange={(event) => setTemplateType(event.target.value)}><option>Receipt</option><option>Invoice</option><option>Quotation</option><option>Product label</option></select></label><label className="field"><span>Paper format</span><select value={paperSize} onChange={(event) => setPaperSize(event.target.value)}><option>80mm thermal</option><option>58mm thermal</option><option>A4</option><option>A5</option></select></label><label className="field"><span>Print density</span><select value={printDensity} onChange={(event) => setPrintDensity(event.target.value)}><option>Compact</option><option>Comfortable</option><option>Spacious</option></select></label><label className="field"><span>Copies per transaction</span><select value={printCopies} onChange={(event) => setPrintCopies(event.target.value)}><option>1</option><option>2</option><option>3</option></select></label></div>
            <div className="template-grid"><TemplateCard name="Modern receipt" description="Compact thermal layout with totals and payment method." selected={selectedTemplate === 'Modern receipt'} onClick={() => setSelectedTemplate('Modern receipt')} /><TemplateCard name="Detailed invoice" description="A4 layout with tax breakdown, customer details, and terms." selected={selectedTemplate === 'Detailed invoice'} onClick={() => setSelectedTemplate('Detailed invoice')} /><TemplateCard name="Minimal receipt" description="Fast checkout print with only essential transaction details." selected={selectedTemplate === 'Minimal receipt'} onClick={() => setSelectedTemplate('Minimal receipt')} /></div>
            <div className="print-preview-layout"><div className="print-preview" style={{ borderTopColor: accentColor }}><div className="print-preview-header"><strong style={{ color: accentColor }}>{printSettings.showLogo ? businessName : 'Sales document'}</strong><span>{templateType} · {paperSize}</span></div><div className="preview-rule" /><div className="preview-line"><span>2.5mm Twin Cable x1</span><strong>KES 8,500</strong></div><div className="preview-line"><span>LED Bulb 12W x2</span><strong>KES 640</strong></div>{printSettings.showTax && <><div className="preview-rule" /><div className="preview-line"><span>Tax ({taxRate}%)</span><strong>KES 1,462</strong></div></>}<div className="preview-rule" /><div className="preview-line"><span>Total</span><strong>KES 9,140</strong></div>{printSettings.showCustomer && <p>Customer: Walk-in customer</p>}<p>{receiptFooter}</p></div><div className="print-options"><div className="settings-option-heading"><div><strong>Document content</strong><span>Choose the details your customers see.</span></div><label className="field compact-field"><span>Accent color</span><input type="color" value={accentColor} onChange={(event) => setAccentColor(event.target.value)} /></label></div><div className="settings-toggle-list"><Toggle label="Show business identity" description="Include your business name and logo area at the top." checked={printSettings.showLogo} onChange={() => togglePrintSetting('showLogo')} /><Toggle label="Show tax breakdown" description="Print tax rate and tax amount before the final total." checked={printSettings.showTax} onChange={() => togglePrintSetting('showTax')} /><Toggle label="Show customer details" description="Include the customer name or walk-in customer label." checked={printSettings.showCustomer} onChange={() => togglePrintSetting('showCustomer')} /><Toggle label="Auto-print after payment" description="Send a receipt to the configured printer after checkout." checked={printSettings.autoPrint} onChange={() => togglePrintSetting('autoPrint')} /><Toggle label="Open cash drawer after sale" description="Trigger the connected drawer when a cash sale completes." checked={printSettings.openDrawer} onChange={() => togglePrintSetting('openDrawer')} /></div></div></div>
          </>}
          {activeSection === 'business' && <><div className="settings-section-header"><div><p className="eyebrow">Business profile</p><h3>Company identity</h3><p>These details appear on receipts, invoices, and customer communications.</p></div><span className="status-badge success">Verified business</span></div><div className="settings-form-grid"><label className="field"><span>Business name</span><input value={businessName} onChange={(event) => setBusinessName(event.target.value)} /></label><label className="field"><span>Business email</span><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="field"><span>Phone number</span><input defaultValue="+254 712 000 111" /></label><label className="field"><span>Business type</span><select defaultValue="Retail & wholesale"><option>Retail & wholesale</option><option>Retail</option><option>Services</option><option>Manufacturing</option></select></label><label className="field"><span>Address</span><input defaultValue="Mombasa Road, Nairobi" /></label><label className="field"><span>Tax PIN</span><input defaultValue="P051234567X" /></label></div></>}

          {activeSection === 'finance' && <><div className="settings-section-header"><div><p className="eyebrow">Finance</p><h3>Taxes & pricing</h3><p>Control how prices, taxes, and totals are calculated throughout the workspace.</p></div></div><div className="settings-form-grid"><label className="field"><span>Default currency</span><select value={currency} onChange={(event) => setCurrency(event.target.value)}><option>KES</option><option>USD</option><option>EUR</option><option>GBP</option></select></label><label className="field"><span>Default tax rate (%)</span><input type="number" min="0" value={taxRate} onChange={(event) => setTaxRate(event.target.value)} /></label><label className="field"><span>Price display</span><select defaultValue="Tax exclusive"><option>Tax exclusive</option><option>Tax inclusive</option></select></label><label className="field"><span>Decimal precision</span><select defaultValue="2 decimal places"><option>0 decimal places</option><option>2 decimal places</option></select></label><label className="field"><span>Low margin warning</span><input defaultValue="15" type="number" /></label><label className="field"><span>Payment terms</span><select defaultValue="Due on receipt"><option>Due on receipt</option><option>7 days</option><option>30 days</option></select></label></div></>}

          {activeSection === 'sales' && <><div className="settings-section-header"><div><p className="eyebrow">Sales & receipts</p><h3>Checkout defaults</h3><p>Set the defaults your team uses when creating sales and issuing receipts.</p></div></div><div className="settings-form-grid"><label className="field"><span>Receipt footer</span><input value={receiptFooter} onChange={(event) => setReceiptFooter(event.target.value)} /></label><label className="field"><span>Invoice prefix</span><input defaultValue="INV-" /></label><label className="field"><span>Default payment method</span><select defaultValue="M-Pesa"><option>M-Pesa</option><option>Cash</option><option>Card</option><option>Credit</option></select></label><label className="field"><span>Default branch</span><select defaultValue="Main Branch"><option>Main Branch</option><option>Industrial Area</option></select></label></div><div className="settings-toggle-list"><Toggle label="Require customer on credit sales" description="Prevent credit transactions without a customer account." checked={settings.requireCustomer} onChange={() => toggle('requireCustomer')} /><Toggle label="Allow negative stock" description="Allow checkout to continue when stock reaches zero." checked={settings.negativeStock} onChange={() => toggle('negativeStock')} /></div></>}

          {activeSection === 'peripherals' && <><div className="settings-section-header"><div><p className="eyebrow">POS hardware</p><h3>Peripherals & devices</h3><p>Connect and configure the equipment used at each checkout register.</p></div><span className="status-badge success">Register 01 ready</span></div><div className="peripheral-grid"><PeripheralCard name="Receipt printer" detail="Epson TM-T20III · USB" connected={peripherals.printer} onChange={() => setPeripherals((current) => ({ ...current, printer: !current.printer }))} /><PeripheralCard name="Barcode scanner" detail="Honeywell Voyager · USB" connected={peripherals.scanner} onChange={() => setPeripherals((current) => ({ ...current, scanner: !current.scanner }))} /><PeripheralCard name="Cash drawer" detail="APG Vasario · Printer kick" connected={peripherals.drawer} onChange={() => setPeripherals((current) => ({ ...current, drawer: !current.drawer }))} /><PeripheralCard name="Customer display" detail="Secondary screen · HDMI" connected={peripherals.display} onChange={() => setPeripherals((current) => ({ ...current, display: !current.display }))} /><PeripheralCard name="Weighing scale" detail="Retail scale · Serial" connected={peripherals.scale} onChange={() => setPeripherals((current) => ({ ...current, scale: !current.scale }))} /></div><div className="settings-form-grid"><label className="field"><span>Active register</span><select defaultValue="Register 01 · Main Branch"><option>Register 01 · Main Branch</option><option>Register 02 · Main Branch</option><option>Register 03 · Industrial Area</option></select></label><label className="field"><span>Scanner input mode</span><select defaultValue="Keyboard wedge"><option>Keyboard wedge</option><option>Serial / COM</option><option>Manual SKU entry</option></select></label><label className="field"><span>Printer connection</span><select defaultValue="USB"><option>USB</option><option>Network</option><option>Bluetooth</option></select></label><label className="field"><span>Cash drawer trigger</span><select defaultValue="Open after cash payment"><option>Open after cash payment</option><option>Open for every sale</option><option>Manual only</option></select></label></div><div className="settings-toggle-list"><Toggle label="Test print after connection" description="Print a test receipt whenever a new printer is connected." checked={true} onChange={() => undefined} /><Toggle label="Require scanner confirmation" description="Play a sound and show feedback after every successful scan." checked={settings.sounds} onChange={() => toggle('sounds')} /></div></>}

          {activeSection === 'templates' && <><div className="settings-section-header"><div><p className="eyebrow">Print center</p><h3>Templates & printing</h3><p>Choose branded layouts for receipts, invoices, quotations, and product labels.</p></div><button className="secondary-button small" type="button" onClick={() => setSaved(true)}>Save template</button></div><div className="template-toolbar"><label className="field"><span>Template type</span><select value={templateType} onChange={(event) => setTemplateType(event.target.value)}><option>Receipt</option><option>Invoice</option><option>Quotation</option><option>Product label</option></select></label><label className="field"><span>Paper format</span><select value={paperSize} onChange={(event) => setPaperSize(event.target.value)}><option>80mm thermal</option><option>58mm thermal</option><option>A4</option><option>A5</option></select></label></div><div className="template-grid"><TemplateCard name="Modern receipt" description="Compact thermal layout with totals and payment method." selected={selectedTemplate === 'Modern receipt'} onClick={() => setSelectedTemplate('Modern receipt')} /><TemplateCard name="Detailed invoice" description="A4 layout with tax breakdown, customer details, and terms." selected={selectedTemplate === 'Detailed invoice'} onClick={() => setSelectedTemplate('Detailed invoice')} /><TemplateCard name="Minimal receipt" description="Fast checkout print with only essential transaction details." selected={selectedTemplate === 'Minimal receipt'} onClick={() => setSelectedTemplate('Minimal receipt')} /></div><div className="print-preview-layout"><div className="print-preview"><div className="print-preview-header"><strong>{businessName}</strong><span>{templateType} · {paperSize}</span></div><div className="preview-rule" /><div className="preview-line"><span>2.5mm Twin Cable x1</span><strong>KES 8,500</strong></div><div className="preview-line"><span>LED Bulb 12W x2</span><strong>KES 640</strong></div><div className="preview-rule" /><div className="preview-line"><span>Total</span><strong>KES 9,140</strong></div><p>{receiptFooter}</p></div><div className="settings-toggle-list print-options"><Toggle label="Show business logo" description="Include the registered logo at the top of every document." checked={true} onChange={() => undefined} /><Toggle label="Show cashier name" description="Print the responsible cashier on receipts and invoices." checked={true} onChange={() => undefined} /><Toggle label="Auto-print after payment" description="Send a receipt to the configured printer after checkout." checked={true} onChange={() => undefined} /><Toggle label="Print customer copy" description="Print a second copy when a customer is attached to the sale." checked={false} onChange={() => undefined} /></div></div></>}

          {activeSection === 'notifications' && <><div className="settings-section-header"><div><p className="eyebrow">Notifications</p><h3>Stay informed</h3><p>Choose which events should reach your team and where they should be delivered.</p></div></div><div className="settings-toggle-list"><Toggle label="Low-stock alerts" description="Notify inventory managers when products reach their reorder point." checked={settings.lowStock} onChange={() => toggle('lowStock')} /><Toggle label="Daily sales summary" description="Send a daily performance summary to business owners." checked={settings.dailySummary} onChange={() => toggle('dailySummary')} /><Toggle label="Payment alerts" description="Notify managers when a payment or refund is completed." checked={settings.paymentAlerts} onChange={() => toggle('paymentAlerts')} /></div><div className="settings-form-grid"><label className="field"><span>Alert email</span><input type="email" defaultValue="alerts@mwangi-electricals.co.ke" /></label><label className="field"><span>Summary delivery time</span><input type="time" defaultValue="18:00" /></label></div></>}

          {activeSection === 'security' && <><div className="settings-section-header"><div><p className="eyebrow">Security & access</p><h3>Protect your workspace</h3><p>Manage sign-in requirements and review access controls for your team.</p></div><span className="status-badge success">Secure session</span></div><div className="settings-toggle-list"><Toggle label="Two-factor authentication" description="Require a verification code for owner and manager sign-ins." checked={settings.twoFactor} onChange={() => toggle('twoFactor')} /><Toggle label="Session expiry" description="Sign users out after 8 hours of inactivity." checked={settings.sessionExpiry} onChange={() => toggle('sessionExpiry')} /><Toggle label="Login notifications" description="Notify owners when a new device signs in." checked={settings.loginNotifications} onChange={() => toggle('loginNotifications')} /></div><div className="settings-action-row"><div><strong>Team permissions</strong><span>Review roles and page access for every team member.</span></div><button className="secondary-button small" type="button" onClick={() => setShowPermissions((current) => !current)}>{showPermissions ? 'Hide permissions' : 'Manage permissions'}</button></div>{showPermissions && <div className="permissions-preview">{[['Owner', 'All modules'], ['Manager', 'Operations and reports'], ['Inventory Manager', 'Products and stock'], ['Cashier', 'POS and sales'], ['Accountant', 'Finance and reports']].map(([role, access]) => <div key={role}><strong>{role}</strong><span>{access}</span></div>)}</div>}</>}

          {activeSection === 'backups' && <><div className="settings-section-header"><div><p className="eyebrow">Backups & audit</p><h3>Data protection</h3><p>Keep your business records recoverable and your operational history traceable.</p></div></div><div className="backup-status"><div><strong>Last backup completed</strong><span>{lastBackup} · All business data protected</span></div><div className="backup-actions"><span className="status-badge success">Healthy</span><button className="secondary-button small" type="button" onClick={runBackup}>Run backup</button></div></div><div className="settings-toggle-list"><Toggle label="Automatic daily backups" description="Create a protected backup of your business data every night." checked={settings.autoBackup} onChange={() => toggle('autoBackup')} /><Toggle label="Audit activity log" description="Record changes to sales, stock, settings, and user permissions." checked={settings.auditLog} onChange={() => toggle('auditLog')} /></div><div className="settings-action-row"><div><strong>Export business data</strong><span>Download a copy of your current business records.</span></div><button className="secondary-button small" type="button" onClick={exportData}>Download export</button></div></>}

          {activeSection === 'integrations' && <><div className="settings-section-header"><div><p className="eyebrow">Integrations</p><h3>Connected tools</h3><p>Connect the services your business uses to keep workflows in sync.</p></div></div><div className="integration-list"><div className="integration-row"><div className="integration-icon">M</div><div><strong>M-Pesa payments</strong><span>Accept mobile payments at checkout</span></div><span className={`status-badge ${integrations.mpesa ? 'success' : 'neutral'}`}>{integrations.mpesa ? 'Connected' : 'Available'}</span><button className="ghost-button small" type="button" onClick={() => setIntegrations((current) => ({ ...current, mpesa: !current.mpesa }))}>{integrations.mpesa ? 'Disconnect' : 'Connect'}</button></div><div className="integration-row"><div className="integration-icon">E</div><div><strong>Email delivery</strong><span>Receipts and alerts via email</span></div><span className={`status-badge ${integrations.email ? 'success' : 'neutral'}`}>{integrations.email ? 'Connected' : 'Available'}</span><button className="ghost-button small" type="button" onClick={() => setIntegrations((current) => ({ ...current, email: !current.email }))}>{integrations.email ? 'Disconnect' : 'Connect'}</button></div><div className="integration-row"><div className="integration-icon">S</div><div><strong>SMS notifications</strong><span>Customer payment and order messages</span></div><span className={`status-badge ${integrations.sms ? 'success' : 'neutral'}`}>{integrations.sms ? 'Connected' : 'Available'}</span><button className="secondary-button small" type="button" onClick={() => setIntegrations((current) => ({ ...current, sms: !current.sms }))}>{integrations.sms ? 'Disconnect' : 'Connect'}</button></div></div></>}

          {activeSection === 'appearance' && <><div className="settings-section-header"><div><p className="eyebrow">Theme & layout</p><h3>Workspace preferences</h3><p>Choose a theme for this device. Your preference is saved automatically.</p></div></div><div className="theme-choice-row"><button className={`theme-choice ${theme === 'light' ? 'active' : ''}`} type="button" onClick={() => setTheme('light')}><span className="theme-preview light-preview" />Light<span>Light theme</span></button><button className={`theme-choice ${theme === 'dark' ? 'active' : ''}`} type="button" onClick={() => setTheme('dark')}><span className="theme-preview dark-preview" />Dark<span>Dark theme</span></button><button className={`theme-choice ${theme === 'system' ? 'active' : ''}`} type="button" onClick={() => setTheme('system')}><span className="theme-preview system-preview" />System<span>Follow device</span></button></div><div className="settings-toggle-list"><Toggle label="Compact tables" description="Fit more rows into sales and inventory tables." checked={settings.compactMode} onChange={() => toggle('compactMode')} /><Toggle label="POS sounds" description="Play a subtle sound when items are added at the register." checked={settings.sounds} onChange={() => toggle('sounds')} /></div></>}

          <div className="settings-danger"><div><strong>Danger zone</strong><span>{confirmDeactivate ? 'Click again to confirm deactivation.' : 'Destructive actions require owner confirmation.'}</span></div><button className="danger-button small" type="button" onClick={() => setConfirmDeactivate((current) => !current)}>{confirmDeactivate ? 'Confirm deactivation' : 'Deactivate workspace'}</button></div>
        </section>
      </div>
    </div>
  );
}
