import { useMemo, useState } from 'react';

type CollectionStatus = 'On track' | 'Due soon' | 'Critical' | 'Disputed' | 'Paid';
type Collection = { id: number; customer: string; invoice: string; amount: number; paid: number; dueDate: string; age: string; branch: string; status: CollectionStatus; lastContact: string };

const initialCollections: Collection[] = [
  { id: 1, customer: 'James Njoroge', invoice: 'INV-00471', amount: 42000, paid: 0, dueDate: '24 Sep 2026', age: '2 days', branch: 'Main Branch', status: 'Due soon', lastContact: 'Never' },
  { id: 2, customer: 'Lilian Atieno', invoice: 'INV-00460', amount: 61500, paid: 30000, dueDate: '27 Sep 2026', age: '5 days', branch: 'Main Branch', status: 'On track', lastContact: 'Yesterday' },
  { id: 3, customer: 'Brian Otieno', invoice: 'INV-00422', amount: 18900, paid: 0, dueDate: '21 Sep 2026', age: '1 day overdue', branch: 'Industrial Area', status: 'Critical', lastContact: '3 days ago' },
  { id: 4, customer: 'Sunset Homes', invoice: 'INV-00398', amount: 72500, paid: 0, dueDate: '10 Sep 2026', age: '12 days overdue', branch: 'Main Branch', status: 'Critical', lastContact: 'Today' },
  { id: 5, customer: 'Hydra Construction', invoice: 'INV-00405', amount: 9400, paid: 0, dueDate: '29 Sep 2026', age: '7 days', branch: 'Industrial Area', status: 'Disputed', lastContact: '2 days ago' },
];

const money = (amount: number) => `KES ${amount.toLocaleString('en-KE')}`;

export function Collections() {
  const [collections, setCollections] = useState(initialCollections);
  const [selectedId, setSelectedId] = useState(1);
  const [filter, setFilter] = useState('All accounts');
  const [search, setSearch] = useState('');
  const [showPayment, setShowPayment] = useState(false);
  const [paymentAmount, setPaymentAmount] = useState('');
  const [notice, setNotice] = useState('');
  const selected = collections.find((entry) => entry.id === selectedId) ?? collections[0];
  const visible = useMemo(() => collections.filter((entry) => (filter === 'All accounts' || entry.status === filter) && `${entry.customer} ${entry.invoice} ${entry.branch}`.toLowerCase().includes(search.toLowerCase())), [collections, filter, search]);
  const outstanding = collections.reduce((sum, entry) => sum + entry.amount - entry.paid, 0);
  const overdue = collections.filter((entry) => entry.status === 'Critical').reduce((sum, entry) => sum + entry.amount - entry.paid, 0);
  const dueSoon = collections.filter((entry) => entry.status === 'Due soon').reduce((sum, entry) => sum + entry.amount - entry.paid, 0);
  const recordPayment = () => { const amount = Number(paymentAmount); if (!Number.isFinite(amount) || amount <= 0) return; setCollections((current) => current.map((entry) => { if (entry.id !== selected.id) return entry; const paid = Math.min(entry.amount, entry.paid + amount); return { ...entry, paid, status: paid >= entry.amount ? 'Paid' : entry.status === 'Critical' ? 'Critical' : 'On track' }; })); setPaymentAmount(''); setShowPayment(false); setNotice(`Payment recorded for ${selected.customer}`); };
  const sendReminder = () => { setCollections((current) => current.map((entry) => entry.id === selected.id ? { ...entry, lastContact: 'Just now' } : entry)); setNotice(`Reminder sent to ${selected.customer}`); };
  const exportSchedule = () => { const csv = [['Customer', 'Invoice', 'Amount', 'Paid', 'Balance', 'Due date', 'Status'], ...collections.map((entry) => [entry.customer, entry.invoice, String(entry.amount), String(entry.paid), String(entry.amount - entry.paid), entry.dueDate, entry.status])].map((row) => row.join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'bizos-collections.csv'; link.click(); URL.revokeObjectURL(url); setNotice('Collections schedule exported'); };

  return (
    <div className="collections-workspace">
      <div className="panel collections-header"><div><p className="eyebrow">Receivables management</p><h3>Collections</h3><p className="panel-subtitle">Track customer balances, prioritize overdue accounts, and record payment follow-ups.</p></div><div className="collections-header-actions"><button className="secondary-button small" type="button" onClick={exportSchedule}>Export schedule</button><button className="primary-button small" type="button" onClick={() => setShowPayment(true)}>Record payment</button></div></div>
      <div className="collection-kpis"><div className="stat-card compact"><div className="stat-header"><span>Total outstanding</span><span className="trend down">Review</span></div><div className="stat-value">{money(outstanding)}</div><div className="stat-footer">Across {collections.length} invoices</div></div><div className="stat-card compact"><div className="stat-header"><span>Overdue</span></div><div className="stat-value">{money(overdue)}</div><div className="stat-footer">Critical follow-up required</div></div><div className="stat-card compact"><div className="stat-header"><span>Due soon</span></div><div className="stat-value">{money(dueSoon)}</div><div className="stat-footer">Due within 7 days</div></div><div className="stat-card compact"><div className="stat-header"><span>Collection rate</span><span className="trend up">+6.2%</span></div><div className="stat-value">68%</div><div className="stat-footer">This month</div></div></div>
      <div className="aging-grid"><div className="aging-card current"><span>Current</span><strong>{money(collections.filter((entry) => entry.status === 'On track').reduce((sum, entry) => sum + entry.amount - entry.paid, 0))}</strong><small>Not yet due</small></div><div className="aging-card soon"><span>Due soon</span><strong>{money(dueSoon)}</strong><small>Next 7 days</small></div><div className="aging-card overdue"><span>1-30 days overdue</span><strong>{money(overdue)}</strong><small>Needs contact</small></div><div className="aging-card disputed"><span>Disputed</span><strong>{money(collections.filter((entry) => entry.status === 'Disputed').reduce((sum, entry) => sum + entry.amount - entry.paid, 0))}</strong><small>Resolve before chase</small></div></div>
      <div className="collection-layout"><div className="panel"><div className="collection-toolbar"><div><p className="eyebrow">Receivables ledger</p><h3>Accounts to collect</h3></div><div className="collection-filters"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search customer or invoice" aria-label="Search collections" /><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Collection status"><option>All accounts</option><option>On track</option><option>Due soon</option><option>Critical</option><option>Disputed</option><option>Paid</option></select></div></div><div className="collection-table"><table><thead><tr><th>Customer</th><th>Invoice</th><th>Balance</th><th>Due</th><th>Last contact</th><th>Status</th></tr></thead><tbody>{visible.map((entry) => <tr key={entry.id} className={selectedId === entry.id ? 'selected-row' : ''} onClick={() => setSelectedId(entry.id)}><td><strong>{entry.customer}</strong><small className="table-secondary">{entry.branch}</small></td><td>{entry.invoice}</td><td><strong>{money(entry.amount - entry.paid)}</strong></td><td>{entry.age}</td><td>{entry.lastContact}</td><td><span className={`status-badge ${entry.status === 'Critical' ? 'danger' : entry.status === 'Due soon' || entry.status === 'Disputed' ? 'warning' : entry.status === 'Paid' ? 'success' : 'neutral'}`}>{entry.status}</span></td></tr>)}</tbody></table></div></div><aside className="panel collection-detail"><div className="panel-header"><div><p className="eyebrow">Account detail</p><h3>{selected.customer}</h3></div><span className={`status-badge ${selected.status === 'Critical' ? 'danger' : selected.status === 'Due soon' || selected.status === 'Disputed' ? 'warning' : 'success'}`}>{selected.status}</span></div><p className="collection-detail-invoice">{selected.invoice} · Due {selected.dueDate}</p><div className="collection-detail-actions"><button className="primary-button small" type="button" onClick={() => setShowPayment(true)}>Record payment</button><button className="secondary-button small" type="button" onClick={sendReminder}>Send reminder</button></div><div className="collection-detail-list"><div><span>Invoice amount</span><strong>{money(selected.amount)}</strong></div><div><span>Paid</span><strong>{money(selected.paid)}</strong></div><div><span>Balance</span><strong>{money(selected.amount - selected.paid)}</strong></div><div><span>Last contact</span><strong>{selected.lastContact}</strong></div><div><span>Branch</span><strong>{selected.branch}</strong></div></div><div className="collection-health"><strong>Collection guidance</strong><span>{selected.status === 'Critical' ? 'Contact the customer today and document the outcome.' : selected.status === 'Disputed' ? 'Resolve the dispute before sending another reminder.' : 'Schedule a reminder before the due date.'}</span></div></aside></div>
      {showPayment && <div className="modal-backdrop" role="presentation"><div className="payment-modal" role="dialog" aria-modal="true" aria-labelledby="collection-payment-title"><div className="modal-header"><div><p className="eyebrow">Receivable payment</p><h3 id="collection-payment-title">Record payment</h3></div><button className="icon-button" type="button" onClick={() => setShowPayment(false)}>×</button></div><div className="payment-total">{money(selected.amount - selected.paid)}<small>{selected.customer} · {selected.invoice}</small></div><label className="field payment-field"><span>Amount received</span><input autoFocus type="number" min="1" value={paymentAmount} onChange={(event) => setPaymentAmount(event.target.value)} placeholder="Enter amount" /></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={() => setShowPayment(false)}>Cancel</button><button className="primary-button" type="button" onClick={recordPayment}>Apply payment</button></div></div></div>}
      {notice && <div className="pos-notice" role="status">{notice}</div>}
    </div>
  );
}
