import { escapeHtml, money } from './printHtml';

export interface ReportMeta {
  businessName: string;
  logoUrl?: string | null;
  currency: string;
  rangeLabel: string;
  branchLabel?: string;
  generatedAt: string;
}

export type ReportSection =
  | {
      kind: 'summary';
      title: string;
      rows: Array<{ label: string; value: string }>;
    }
  | {
      kind: 'table';
      title: string;
      columns: string[];
      rows: string[][];
      total?: string;
    };

export interface ReportInput {
  meta: Partial<ReportMeta> & { currency: string; rangeLabel: string };
  sections: ReportSection[];
}

export function reportsHtml(input: ReportInput): string {
  const meta: ReportMeta = {
    businessName: 'BizOS',
    logoUrl: null,
    currency: 'KES',
    rangeLabel: 'This period',
    branchLabel: undefined,
    generatedAt: new Date().toISOString(),
    ...input.meta,
  };

  const sections = Array.isArray(input.sections) ? input.sections : [];
  const lines: string[] = [];

  lines.push('<div class="report">');

  lines.push('<div class="report-header">');
  if (meta.logoUrl) {
    lines.push(
      `<img class="logo" src="${escapeHtml(meta.logoUrl)}" alt="${escapeHtml(
        meta.businessName
      )}" />`
    );
  }
  lines.push(`<h1>${escapeHtml(meta.businessName)}</h1>`);
  lines.push(
    `<p class="center muted small">${escapeHtml(meta.rangeLabel)}${
      meta.branchLabel ? ` · ${escapeHtml(meta.branchLabel)}` : ''
    }</p>`
  );
  lines.push(
    `<p class="center muted small">Generated ${escapeHtml(
      new Date(meta.generatedAt).toLocaleString()
    )}</p>`
  );
  lines.push('</div>');

  for (const section of sections) {
    lines.push('<div class="report-section">');
    lines.push(`<h2>${escapeHtml(section.title)}</h2>`);

    if (section.kind === 'summary') {
      lines.push('<table><tbody>');
      for (const row of section.rows || []) {
        lines.push(
          `<tr><td class="label">${escapeHtml(row.label)}</td><td class="num">${escapeHtml(
            row.value
          )}</td></tr>`
        );
      }
      lines.push('</tbody></table>');
    }

    if (section.kind === 'table') {
      lines.push('<table><thead><tr>');
      for (const col of section.columns || []) {
        lines.push(`<th>${escapeHtml(col)}</th>`);
      }
      lines.push('</tr></thead><tbody>');
      for (const row of section.rows || []) {
        lines.push('<tr>');
        row.forEach((cell, i) => {
          const isNum = /^-?[\d,.\s]+$/.test(cell);
          lines.push(
            `<td class="${isNum && i > 0 ? 'num' : ''}">${escapeHtml(cell)}</td>`
          );
        });
        lines.push('</tr>');
      }
      lines.push('</tbody>');
      if (section.total) {
        lines.push(
          `<tfoot><tr><td colspan="${
            (section.columns?.length || 1) - 1
          }" class="num label">Total</td><td class="num total">${escapeHtml(
            section.total
          )}</td></tr></tfoot>`
        );
      }
      lines.push('</table>');
    }

    lines.push('</div>');
  }

  lines.push(
    `<p class="center muted small report-footer">${escapeHtml(
      meta.businessName
    )} · Generated by BizOS</p>`
  );

  lines.push('</div>');

  return lines.join('\n');
}

export function salesSummarySection(input: {
  totalSales: number;
  totalTransactions: number;
  totalDiscount: number;
  totalTax: number;
  currency: string;
}): ReportSection {
  const { totalSales, totalTransactions, totalDiscount, totalTax, currency } = input;
  const avg = totalTransactions > 0 ? totalSales / totalTransactions : 0;
  const rows: Array<{ label: string; value: string }> = [
    { label: 'Total sales', value: money(totalSales, currency) },
    { label: 'Transactions', value: String(totalTransactions) },
    { label: 'Average order', value: money(avg, currency) },
    { label: 'Total discount', value: money(totalDiscount, currency) },
  ];
  if (totalTax > 0) {
    rows.push({ label: 'Total VAT', value: money(totalTax, currency) });
  }
  return { kind: 'summary', title: 'Sales summary', rows };
}

export function topProductsSection(input: {
  rows: Array<{ name: string; qty: number; revenue: number }>;
  currency: string;
}): ReportSection {
  return {
    kind: 'table',
    title: 'Top products',
    columns: ['Product', 'Qty', 'Revenue'],
    rows: input.rows.map((r) => [
      r.name,
      String(r.qty),
      money(r.revenue, input.currency),
    ]),
  };
}

export function staffSection(input: {
  rows: Array<{ name: string; totalSales: number; transactions: number }>;
  currency: string;
}): ReportSection {
  return {
    kind: 'table',
    title: 'Staff performance',
    columns: ['Team member', 'Transactions', 'Sales'],
    rows: input.rows.map((r) => [
      r.name,
      String(r.transactions),
      money(r.totalSales, input.currency),
    ]),
  };
}