import { ArrowRight, BarChart3, Check, CircleDollarSign, PackageCheck, ShoppingCart, Store, Users } from 'lucide-react';
import type { AppPage } from '../../routes/AppRoutes';
import { PublicFooter } from '../../components/layout/public/PublicFooter';

type PublicPageId = 'public-about' | 'public-contact' | 'public-plans' | 'public-product' | 'public-inventory' | 'public-insights';

const pageContent: Record<PublicPageId, { eyebrow: string; title: string; emphasis: string; description: string; icon: typeof ShoppingCart; accent: string; points: string[] }> = {
  'public-product': { eyebrow: 'Point of sale', title: 'A faster counter', emphasis: 'for every sale.', description: 'A focused checkout for scanning, payment, and receipts.', icon: ShoppingCart, accent: 'coral', points: ['Barcode and SKU search', 'M-Pesa, cash, card, and credit'] },
  'public-inventory': { eyebrow: 'Inventory control', title: 'Stock that tells', emphasis: 'the truth.', description: 'Stock, purchasing, suppliers, and branches in one view.', icon: PackageCheck, accent: 'green', points: ['Live stock by branch', 'Reorder point alerts'] },
  'public-insights': { eyebrow: 'Business insights', title: 'Know what happened.', emphasis: 'Choose what happens next.', description: 'Useful reporting for owners and managers.', icon: BarChart3, accent: 'blue', points: ['Revenue and margin trends', 'Branch comparisons'] },
  'public-about': { eyebrow: 'About BizOs', title: 'Built for the', emphasis: 'work behind the work.', description: 'BizOs helps growing businesses make every sale, stock movement, and customer moment easier to understand and act on. We believe good software should make a busy day feel clearer.', icon: Users, accent: 'blue', points: ['One calm operating system', 'Designed around real workflows', 'Made for teams and branches', 'Clear signals instead of busywork'] },
  'public-contact': { eyebrow: 'Talk to BizOs', title: 'Bring us the', emphasis: 'complicated bit.', description: 'Whether you are opening your first register or connecting several branches, our team can help you map the workflow and get moving.', icon: Users, accent: 'amber', points: ['hello@bizos.co.ke', '+254 712 000 111', 'Product walkthroughs', 'Support within one business day'] },
  'public-plans': { eyebrow: 'Plans that grow with you', title: 'Start simple.', emphasis: 'Grow without friction.', description: 'Choose the operating rhythm that fits your business today, then add branches, people, and deeper insight as you grow. Every plan includes core checkout, inventory, and support.', icon: CircleDollarSign, accent: 'green', points: ['Starter · KES 8,900 / month', 'Growth · KES 18,600 / month', 'Scale · KES 39,900 / month', 'No surprise setup costs'] },
};

function PublicNav({ active, onNavigate }: { active: PublicPageId; onNavigate: (page: AppPage) => void }) {
  return <nav className="public-detail-nav"><button className="landing-brand" type="button" onClick={() => onNavigate('landing')}><span className="landing-brand-mark">B</span><span><strong>BizOs</strong><small>Business OS</small></span></button><div className="public-detail-tabs"><button type="button" onClick={() => onNavigate('landing')}>Home</button><button className={active === 'public-about' ? 'active' : ''} type="button" onClick={() => onNavigate('public-about')}>About us</button><button className={active === 'public-contact' ? 'active' : ''} type="button" onClick={() => onNavigate('public-contact')}>Contact</button><button className={active === 'public-plans' ? 'active' : ''} type="button" onClick={() => onNavigate('public-plans')}>Plans</button></div><div className="public-detail-actions"><button type="button" onClick={() => onNavigate('login')}>Sign in</button><button className="primary-button small" type="button" onClick={() => onNavigate('register')}>Start free <ArrowRight size={15} /></button></div></nav>;
}

function PublicFeaturePageView({ page, onNavigate }: { page: PublicPageId; onNavigate: (page: AppPage) => void }) {
  const content = pageContent[page];
  const Icon = content.icon;
  return <main className="public-detail-page"><PublicNav active={page} onNavigate={onNavigate} /><section className="public-detail-hero"><div className="public-detail-copy"><div className={`public-detail-icon ${content.accent}`}><Icon size={24} /></div><p className="landing-kicker">{content.eyebrow}</p><h1>{content.title}<br /><em>{content.emphasis}</em></h1><p>{content.description}</p><div className="public-detail-actions-row"><button className="primary-button large" type="button" onClick={() => onNavigate('register')}>Start with BizOs <ArrowRight size={17} /></button><button className="landing-text-button" type="button" onClick={() => onNavigate('landing')}>Back to overview</button></div></div><div className="public-detail-board"><div className="public-detail-board-top"><span><i /> Live workspace</span><strong>{content.eyebrow}</strong></div><div className="public-detail-board-content"><div className="public-detail-stat"><small>Workspace signal</small><strong>{page === 'public-product' ? 'KES 184,250' : page === 'public-inventory' ? '94.8%' : page === 'public-insights' ? '+12.4%' : '24 hr'}</strong><span>{page === 'public-contact' ? 'Typical response time' : 'Today across your business'}</span></div><div className="public-detail-bars"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="public-detail-checks">{content.points.slice(0, 3).map((point) => <span key={point}><Check size={14} /> {point}</span>)}</div></div></div></section><section className="public-detail-points"><div><p className="landing-section-label"><span>Built in</span><span>to the workflow</span></p><h2>Less switching.<br /><em>More doing.</em></h2></div><div className="public-detail-point-grid">{content.points.map((point, index) => <article key={point}><span>0{index + 1}</span><strong>{point}</strong><p>{page === 'public-product' ? 'Keep the next action close to the sale.' : page === 'public-inventory' ? 'Make the right stock decision at the right time.' : page === 'public-insights' ? 'See the signal behind the transaction.' : 'Get a practical answer from our team.'}</p></article>)}</div></section><section className="public-detail-cta"><Store size={22} /><div><small>One system, built around the work</small><strong>Make your next shift clearer.</strong></div><button className="primary-button" type="button" onClick={() => onNavigate('register')}>Create workspace <ArrowRight size={16} /></button></section></main>;
}

function PublicPageExtras({ page, onNavigate }: { page: PublicPageId; onNavigate: (page: AppPage) => void }) {
  if (page === 'public-plans') return <><section className="public-extra-section"><div className="public-extra-heading"><p className="landing-section-label"><span>Choose your pace</span><span>Simple pricing</span></p><h2>More clarity.<br /><em>Same core.</em></h2></div><div className="public-plan-grid"><article><small>STARTER</small><strong>KES 8,900<span>/month</span></strong><p>For one focused operation getting its rhythm right.</p><button className="secondary-button" type="button" onClick={() => onNavigate('register')}>Choose Starter</button></article><article className="featured"><b>Most popular</b><small>GROWTH</small><strong>KES 18,600<span>/month</span></strong><p>For teams adding branches, people, and better insight.</p><button className="primary-button" type="button" onClick={() => onNavigate('register')}>Choose Growth</button></article><article><small>SCALE</small><strong>KES 39,900<span>/month</span></strong><p>For complex operations that need a unified view.</p><button className="secondary-button" type="button" onClick={() => onNavigate('register')}>Choose Scale</button></article></div></section><section className="public-comparison"><div><p className="landing-section-label"><span>Compare plans</span><span>Included as you grow</span></p><h2>The essentials<br /><em>stay essential.</em></h2></div><div className="public-comparison-table"><div><strong>Core checkout</strong><span>All plans</span></div><div><strong>Inventory and stock alerts</strong><span>All plans</span></div><div><strong>Multi-branch controls</strong><span>Growth and Scale</span></div><div><strong>Advanced reporting</strong><span>Growth and Scale</span></div></div></section></>;
  if (page === 'public-about') return <><section className="public-extra-section public-about-extra"><div className="public-extra-heading"><p className="landing-section-label"><span>Our point of view</span><span>About BizOs</span></p><h2>Software should<br /><em>give time back.</em></h2></div><div className="public-about-diagram"><div><span>01</span><strong>Capture</strong><small>Every sale, movement, and customer moment.</small></div><i /><div><span>02</span><strong>Understand</strong><small>Turn the daily noise into a clear signal.</small></div><i /><div><span>03</span><strong>Act</strong><small>Make the next decision with confidence.</small></div></div></section><section className="public-principles"><p className="landing-section-label"><span>What guides us</span><span>Our principles</span></p><div><article><strong>Clarity over clutter</strong><p>Every screen should help someone decide or do the next thing.</p></article><article><strong>Useful before impressive</strong><p>We build for the shift, the stockroom, and the real question at closing time.</p></article><article><strong>Growth without drama</strong><p>Your systems should get stronger as your operation gets bigger.</p></article></div></section></>;
  return <><section className="public-extra-section public-contact-extra"><div className="public-extra-heading"><p className="landing-section-label"><span>Need a hand</span><span>Contact paths</span></p><h2>One good<br /><em>conversation.</em></h2></div><div className="public-contact-diagram"><div><span className="contact-step active">01</span><strong>Tell us the shape of your operation</strong><small>Branches, registers, people, and the work you want to simplify.</small></div><div><span className="contact-step">02</span><strong>We map the right starting point</strong><small>A practical walkthrough, not a sales maze.</small></div><div><span className="contact-step">03</span><strong>You move forward clearly</strong><small>Email hello@bizos.co.ke or call +254 712 000 111.</small></div></div></section><section className="public-faq"><p className="landing-section-label"><span>Before you write</span><span>Common questions</span></p><div><details><summary>Can BizOs support more than one branch?</summary><p>Yes. Growth and Scale plans connect branches, registers, people, stock, and reporting in one workspace.</p></details><details><summary>Can we get help setting up?</summary><p>Yes. We can walk through your workflow, migration questions, and the best place to start.</p></details><details><summary>How quickly will someone respond?</summary><p>Our team typically responds within one business day during East Africa business hours.</p></details></div></section></>;
}

export function PublicFeaturePage({ page, onNavigate }: { page: PublicPageId; onNavigate: (page: AppPage) => void }) {
  return <><PublicFeaturePageView page={page} onNavigate={onNavigate} /><PublicPageExtras page={page} onNavigate={onNavigate} /><PublicFooter onNavigate={onNavigate} /></>;
}
