import { useState } from 'react';
import { ArrowRight, Check, Mail, ShieldCheck, Users } from 'lucide-react';
import type { AppPage } from '../../../routes/AppRoutes';

export function PublicFooter({ onNavigate }: { onNavigate: (page: AppPage) => void }) {
  const [newsletterSent, setNewsletterSent] = useState(false);

  return <footer className="landing-footer"><div className="landing-footer-main"><div className="landing-footer-intro"><div className="landing-brand"><span className="landing-brand-mark">B</span><span><strong>BizOs</strong><small>Business OS</small></span></div><p>Retail operations,<br />made clear.</p><div className="landing-footer-status"><i /> All systems operational</div><div className="landing-socials"><a href="#workflow" aria-label="BizOs community" title="Community"><Users size={15} /></a><a href="#about" aria-label="BizOs security" title="Security"><ShieldCheck size={15} /></a><a href="#contact" aria-label="Contact BizOs" title="Email us"><Mail size={15} /></a></div></div><div className="landing-footer-column"><strong>Product</strong><a href="#home">Home</a><a href="#about">About us</a><a href="#plans">Plans</a><a href="#contact">Request a demo</a></div><div className="landing-footer-column"><strong>Company</strong><a href="#about">Why BizOs</a><a href="#contact">Contact us</a><button type="button" onClick={() => onNavigate('login')}>Sign in</button><button type="button" onClick={() => onNavigate('register')}>Create workspace</button></div><div className="landing-footer-newsletter"><strong>Useful things, occasionally.</strong><p>Product notes and practical ideas for better operations.</p><form onSubmit={(event) => { event.preventDefault(); setNewsletterSent(true); }}><input type="email" required placeholder="Your work email" aria-label="Your work email" /><button type="submit" aria-label="Subscribe to newsletter">{newsletterSent ? <Check size={16} /> : <ArrowRight size={16} />}</button></form><span>{newsletterSent ? 'You are on the list.' : 'No noise. Unsubscribe anytime.'}</span></div></div><div className="landing-footer-bottom"><span>© 2026 BizOs. Built for businesses in motion.</span><div><a href="#about">Privacy</a><a href="#plans">Terms</a><a href="#contact">Support</a></div><span>Made for the work that matters.</span></div></footer>;
}
